# Generated by Django 6.0.3 on 2026-03-04 03:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('numero_interno', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_fabricacion', models.IntegerField()),
                ('kilometraje', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoBus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad_pasajeros', models.IntegerField()),
                ('longitud_metros', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=20, unique=True)),
                ('turno', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateField()),
                ('bus_asignado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.bus')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='flota.tipobus'),
        ),
    ]
