# Generated by Django 6.0.3 on 2026-05-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['numero_interno'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='conductor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterModelOptions(
            name='tipobus',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Bus', 'verbose_name_plural': 'Tipos de Bus'},
        ),
        migrations.AddField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='tipobus',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='anio_fabricacion',
            field=models.IntegerField(verbose_name='Año de Fabricación'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo'), ('baja', 'Dado de Baja')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='kilometraje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero_interno',
            field=models.CharField(max_length=10, unique=True, verbose_name='N° Interno'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='placa',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='flota.tipobus', verbose_name='Tipo de Bus'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='bus_asignado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor', to='flota.bus', verbose_name='Bus Asignado'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='fecha_contratacion',
            field=models.DateField(verbose_name='Fecha de Contratación'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia',
            field=models.CharField(max_length=20, unique=True, verbose_name='N° Licencia'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('doble', 'Doble Turno')], max_length=10, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='tipobus',
            name='capacidad_pasajeros',
            field=models.IntegerField(verbose_name='Capacidad de Pasajeros'),
        ),
        migrations.AlterField(
            model_name='tipobus',
            name='longitud_metros',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Longitud (m)'),
        ),
        migrations.AlterField(
            model_name='tipobus',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
