# Generated by Django 6.0.3 on 2026-03-04 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTullave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_tarjeta', models.CharField(max_length=20, unique=True)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('cedula_titular', models.CharField(max_length=15, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('bloqueada', 'Bloqueada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('fecha_expedicion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('tipo_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.tipotarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='RecargaTarjeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta Débito'), ('credito', 'Tarjeta Crédito'), ('pse', 'PSE')], max_length=15)),
                ('fecha_recarga', models.DateTimeField(auto_now_add=True)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='usuarios.usuariotullave')),
            ],
        ),
    ]
