# Generated by Django 6.0.3 on 2026-05-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recargatarjeta',
            options={'ordering': ['-fecha_recarga'], 'verbose_name': 'Recarga', 'verbose_name_plural': 'Recargas'},
        ),
        migrations.AlterModelOptions(
            name='tipotarjeta',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Tarjeta', 'verbose_name_plural': 'Tipos de Tarjeta'},
        ),
        migrations.AlterModelOptions(
            name='usuariotullave',
            options={'ordering': ['nombre_titular'], 'verbose_name': 'Usuario Tullave', 'verbose_name_plural': 'Usuarios Tullave'},
        ),
        migrations.AlterField(
            model_name='recargatarjeta',
            name='fecha_recarga',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='recargatarjeta',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta Débito'), ('credito', 'Tarjeta Crédito'), ('app', 'App Móvil'), ('pse', 'PSE')], max_length=15, verbose_name='Medio de Pago'),
        ),
        migrations.AlterField(
            model_name='recargatarjeta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='recargatarjeta',
            name='referencia',
            field=models.CharField(max_length=50, unique=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='recargatarjeta',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Anterior'),
        ),
        migrations.AlterField(
            model_name='recargatarjeta',
            name='saldo_posterior',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Posterior'),
        ),
        migrations.AlterField(
            model_name='recargatarjeta',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='usuarios.usuariotullave', verbose_name='Tarjeta'),
        ),
        migrations.AlterField(
            model_name='tipotarjeta',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipotarjeta',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='tipotarjeta',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuariotullave',
            name='cedula_titular',
            field=models.CharField(max_length=15, unique=True, verbose_name='Cédula Titular'),
        ),
        migrations.AlterField(
            model_name='usuariotullave',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('bloqueada', 'Bloqueada'), ('vencida', 'Vencida'), ('perdida', 'Perdida/Robada')], default='activa', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuariotullave',
            name='fecha_expedicion',
            field=models.DateField(verbose_name='Fecha de Expedición'),
        ),
        migrations.AlterField(
            model_name='usuariotullave',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='usuariotullave',
            name='nombre_titular',
            field=models.CharField(max_length=100, verbose_name='Nombre Titular'),
        ),
        migrations.AlterField(
            model_name='usuariotullave',
            name='numero_tarjeta',
            field=models.CharField(max_length=20, unique=True, verbose_name='N° Tarjeta'),
        ),
        migrations.AlterField(
            model_name='usuariotullave',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='usuariotullave',
            name='tipo_tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.tipotarjeta', verbose_name='Tipo de Tarjeta'),
        ),
    ]
