# Generated by Django 6.0.3 on 2026-03-04 03:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=15)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tiene_biciparqueo', models.BooleanField(default=False)),
                ('tiene_ascensor', models.BooleanField(default=False)),
                ('en_operacion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaEstacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=15)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='estaciones.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='TaquillaCarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('operativa', models.BooleanField(default=True)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taquillas', to='estaciones.estacion')),
            ],
        ),
    ]
