# Generated by Django 6.0.3 on 2026-05-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Estación', 'verbose_name_plural': 'Estaciones'},
        ),
        migrations.AlterModelOptions(
            name='incidenciaestacion',
            options={'ordering': ['-fecha_reporte'], 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
        migrations.AlterModelOptions(
            name='taquillacarga',
            options={'ordering': ['estacion', 'numero'], 'verbose_name': 'Taquilla de Carga', 'verbose_name_plural': 'Taquillas de Carga'},
        ),
        migrations.AlterField(
            model_name='estacion',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='en_operacion',
            field=models.BooleanField(default=True, verbose_name='En Operación'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='localidad',
            field=models.CharField(max_length=100, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='tiene_ascensor',
            field=models.BooleanField(default=False, verbose_name='Ascensor'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='tiene_biciparqueo',
            field=models.BooleanField(default=False, verbose_name='Biciparqueo'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='tipo',
            field=models.CharField(choices=[('portal', 'Portal'), ('troncal', 'Troncal'), ('intermedia', 'Intermedia'), ('sencilla', 'Sencilla')], max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='incidenciaestacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='incidenciaestacion',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='estaciones.estacion', verbose_name='Estación'),
        ),
        migrations.AlterField(
            model_name='incidenciaestacion',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='abierta', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='incidenciaestacion',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte'),
        ),
        migrations.AlterField(
            model_name='incidenciaestacion',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución'),
        ),
        migrations.AlterField(
            model_name='incidenciaestacion',
            name='tipo',
            field=models.CharField(choices=[('infraestructura', 'Infraestructura'), ('seguridad', 'Seguridad'), ('tecnica', 'Técnica'), ('servicio', 'Servicio'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='taquillacarga',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taquillas', to='estaciones.estacion', verbose_name='Estación'),
        ),
        migrations.AlterField(
            model_name='taquillacarga',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='taquillacarga',
            name='operativa',
            field=models.BooleanField(default=True, verbose_name='Operativa'),
        ),
        migrations.AlterField(
            model_name='taquillacarga',
            name='ultima_revision',
            field=models.DateField(blank=True, null=True, verbose_name='Última Revisión'),
        ),
    ]
