# Generated by Django 6.0.3 on 2026-05-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallemantenimiento',
            options={'verbose_name': 'Detalle de Mantenimiento', 'verbose_name_plural': 'Detalles de Mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='ordenmantenimiento',
            options={'ordering': ['-fecha_programada'], 'verbose_name': 'Orden de Mantenimiento', 'verbose_name_plural': 'Órdenes de Mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='repuesto',
            options={'ordering': ['nombre'], 'verbose_name': 'Repuesto', 'verbose_name_plural': 'Repuestos'},
        ),
        migrations.AlterModelOptions(
            name='tipomantenimiento',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Mantenimiento', 'verbose_name_plural': 'Tipos de Mantenimiento'},
        ),
        migrations.AlterField(
            model_name='detallemantenimiento',
            name='cantidad_usada',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallemantenimiento',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mantenimiento.ordenmantenimiento', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='detallemantenimiento',
            name='precio_unitario_momento',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unit.'),
        ),
        migrations.AlterField(
            model_name='detallemantenimiento',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='mantenimiento.repuesto', verbose_name='Repuesto'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='fecha_programada',
            field=models.DateField(verbose_name='Fecha Programada'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='kilometraje_bus',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kilometraje Bus'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='numero_orden',
            field=models.CharField(max_length=20, unique=True, verbose_name='N° Orden'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='placa_bus',
            field=models.CharField(max_length=10, verbose_name='Placa del Bus'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='tecnico_responsable',
            field=models.CharField(max_length=100, verbose_name='Técnico Responsable'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='tipo_mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='mantenimiento.tipomantenimiento', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock_minimo',
            field=models.IntegerField(default=5, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='tipomantenimiento',
            name='categoria',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo'), ('emergencia', 'Emergencia')], max_length=15, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='tipomantenimiento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipomantenimiento',
            name='duracion_estimada_horas',
            field=models.IntegerField(verbose_name='Duración Estimada (h)'),
        ),
        migrations.AlterField(
            model_name='tipomantenimiento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipomantenimiento',
            name='periodicidad_km',
            field=models.IntegerField(blank=True, null=True, verbose_name='Periodicidad (km)'),
        ),
    ]
