# Generated by Django 6.0.3 on 2026-03-04 03:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=100)),
                ('capacidad_buses', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=20)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tiempo_estimado_min', models.IntegerField()),
                ('frecuencia_min', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('portal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='rutas.portal')),
                ('portal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='rutas.portal')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioRuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dias', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutas.ruta')),
            ],
        ),
    ]
