# Generated by Django 6.0.3 on 2026-05-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioruta',
            options={'verbose_name': 'Horario de Ruta', 'verbose_name_plural': 'Horarios de Ruta'},
        ),
        migrations.AlterModelOptions(
            name='portal',
            options={'ordering': ['nombre'], 'verbose_name': 'Portal', 'verbose_name_plural': 'Portales'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['codigo'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterField(
            model_name='horarioruta',
            name='dias',
            field=models.CharField(choices=[('L-V', 'Lunes a Viernes'), ('L-S', 'Lunes a Sábado'), ('L-D', 'Lunes a Domingo'), ('S-D', 'Sábados y Domingos'), ('fes', 'Festivos')], max_length=20, verbose_name='Días'),
        ),
        migrations.AlterField(
            model_name='horarioruta',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora Fin'),
        ),
        migrations.AlterField(
            model_name='horarioruta',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='horarioruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutas.ruta', verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='capacidad_buses',
            field=models.IntegerField(verbose_name='Capacidad de Buses'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='localidad',
            field=models.CharField(max_length=100, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='ubicacion',
            field=models.CharField(max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Distancia (km)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='frecuencia_min',
            field=models.IntegerField(verbose_name='Frecuencia (min)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='portal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='rutas.portal', verbose_name='Portal Destino'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='portal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='rutas.portal', verbose_name='Portal Origen'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tiempo_estimado_min',
            field=models.IntegerField(verbose_name='Tiempo Estimado (min)'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tipo',
            field=models.CharField(choices=[('troncal', 'Troncal'), ('alimentadora', 'Alimentadora'), ('express', 'Express'), ('complementaria', 'Complementaria'), ('dual', 'Dual')], max_length=20, verbose_name='Tipo'),
        ),
    ]
